[local]
environment_prefix = "local"
db_connection = "storage/api-golang-staging.db"
allow_origins = ["http://localhost:3000/"]
client_url="http://localhost:3000"
server_port=7171
uploaded_file_path = "uploaded"
default_page_num = 1
default_page_limit = 10

[dev]
environment_prefix = "dev"
db_connection = "storage/api-golang-staging.db"
allow_origins = [""]
client_url="*"
server_port=7171
uploaded_file_path = "uploaded"
default_page_num = 1
default_page_limit = 10
